base_config: base.yml
model_name: mixtral-8x7b
base_num_decoder_layers: 2
run_name: gpu_train_test
hardware: gpu
steps: 20
per_device_batch_size: 8
max_target_length: 1024
attention: dot_product
remat_policy: full
use_iota_embed: true
dataset_type: synthetic
megablox: false
sparse_matmul: false
dtype: bfloat16
weight_dtype: bfloat16
enable_goodput_recording: false
monitor_goodput: false
scan_layers: false
enable_checkpointing: false
capacity_factor: 1
ici_fsdp_parallelism: 1
ici_data_parallelism: 1
ici_expert_parallelism: -1
