base_config: base.yml

model_name: gemma-2b
run_name: gemma_gpu_train_test
hardware: gpu
base_emb_dim: 512
base_num_query_heads: 4
base_num_kv_heads: 1
base_mlp_dim: 512
base_num_decoder_layers: 2
head_dim: 16
steps: 20
max_target_length: 1028
per_device_batch_size: 4
mlp_activations:
  - gelu
  - linear
vocab_size: 1024
gecoder_block: gemma
dataset_type: synthetic
use_iota_embed: true
scan_layers: false
dtype: bfloat16
weight_dtype: bfloat16
enable_goodput_recording: false
monitor_goodput: false
attention: dot_product
base_output_directory: /tmp
