# model config for llama3.1-8b
base_config: "base.yml"

steps: 15
hardware: "gpu"
model_name: "llama3.1-8b"
dataset_type: "synthetic"
attention: "dot_product"
enable_checkpointing: False
max_segments_per_seq: 32

base_emb_dim: 4096
base_num_query_heads: 32
base_num_kv_heads: 8
base_num_decoder_layers: 32
base_mlp_dim: 14336
head_dim: 128
mlp_activations: ["silu","linear"]
vocab_size: 128256
enable_dropout: false
logits_via_embedding: false
normalization_layer_epsilon: 1.0e-5
rope_max_timescale: 500_000
decoder_block: "llama2" # Uses the same decoder block as llama2
